import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {

    in property <string> results: "";
    callback marksCalc(string, string, string);

    background: #313e50;
    GridLayout {
        padding: 5px;
        spacing: 25px;
        Row {
            Text {
                text: "Pass/fail detector";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }

        Row {

            maths := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Enter your marks for math";
                height: 35px;
            }
        }

        Row {

            science := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Enter your marks for science";
                height: 35px;
            }
        }

        Row {

            computer := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Enter your marks for computer";
                height: 35px;
            }
        }

        Row {
            Button {
                text: "calculate";
                primary: true;
                height: 35px;
                clicked => {
                    marksCalc(science.text, maths.text, computer.text)
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
